### ISSUE TITLE
CCT crashes on startup. 

### ISSUE THREAD

**Issue by toErIpNid** [CammiePone/Cammies-Combat-Tweaks#23] opened 2022-05-09 02:28 UTC
LOG: https://pastebin.com/2awUdtYy

Fabric Ver: 0.14.4

MC Ver: 1.18.2

Mod Ver: 1.11

**Comment by CammiePone** [comment] 2022-05-09 02:30
Duplicate of #22, waiting for Fabric API to accept a PR so I can actually do something about this

**Closed as completed by CammiePone** 2022-05-09 02:30 UTC
